const CartActionTypes = {
  TOGGLE_DROPDOWN: "TOGGLE_DROPDOWN",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM: "CLEAR_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART: "CLEAR_CART",
  CART_FETCH_SUCCESS: "CART_FETCH_SUCCESS",
  CART_FETCH_FAILURE: "CART_FETCH_FAILURE",
};

export default CartActionTypes;
